// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	"github.com/valyala/fasthttp"
	"mediversepreip/internal/controllers"
	"mediversepreip/internal/models"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/doctors",
			Methods:    []string{},
			Controller: &controllers.DoctorsController{},
			Model:      models.Doctors{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello",
			Methods:    []string{fasthttp.MethodGet, fasthttp.MethodPost},
			Controller: &controllers.HelloWorldController{},
		},
	})
}
